### ISSUE TITLE
the default username & password is?

### ISSUE THREAD

**Issue by ilovin** [mphin/miwifi_tools#1]
I've tried 
- password
- admin
both not work

device : redmi ax5400 gaming
and running your script to get the return code
```
{"code":0}{ "code": 0, "msg": "", "id": 6 }{ "code": 0, "msg": "" }{ "code": 0, "msg": "", "id": 7 }{ "code": 0, "msg": "" }{ "code": 0, "msg": "", "id": 8 }{ "code": 0, "msg": "" }{ "code": 0, "msg": "", "id": 9 }{ "code": 0, "msg": "" }{ "code": 0, "msg": "", "id": 10 }{ "code": 0, "msg": "" }
```

**Comment by mphin** [comment]
> I've tried 
> 
> - password
> 
> - admin
> 
> both not work
> 
> 

[MiWiFi SSH Password Calculator](https://miwifi.dev/ssh)
