### ISSUE TITLE
ax5400如何添加dns解析，重启不丢失

### ISSUE THREAD

**Issue by luoyanghero** [mphin/miwifi_tools#2]
感谢分享！
比如添加一条
192.168.31.50 abcde.cn
使用ssh添加，应该放到哪个文件，重启才不会丢失

**Comment by mphin** [comment]
官固直接使用手机APP的自定义hosts不就好了吗

**Comment by luoyanghero** [comment]
> 官固直接使用手机APP的自定义hosts不就好了吗

确实可以^_^.
发现是添加到这两个文件了。
```
/etc/custom_hosts:2:192.168.31.40 zyym.ie
/tmp/hosts/custom_hosts:2:192.168.31.40 zyym.ie
```
我手动修改这个两个文件，重启失效。不知道官固是存放在哪里的。
另外ssh开启后，可以添加自定义脚本，能够添加科学上网脚本吗？

**Comment by mphin** [comment]
> > 官固直接使用手机APP的自定义hosts不就好了吗
> 
> 确实可以^_^. 发现是添加到这两个文件了。
> 
> ```
> /etc/custom_hosts:2:192.168.31.40 zyym.ie
> /tmp/hosts/custom_hosts:2:192.168.31.40 zyym.ie
> ```
> 
> 我手动修改这个两个文件，重启失效。不知道官固是存放在哪里的。 另外ssh开启后，可以添加自定义脚本，能够添加科学上网脚本吗？

我是Ax5400电竞版，没做任何修改默认/etc/custom_hosts是链接到/data/etc/custom_hosts文件的，我试了修改重启后还在呀。

自定义脚本可以[通过防火墙添加](https://github.com/mphin/miwifi_tools?tab=readme-ov-file#%E9%80%9A%E8%BF%87%E9%98%B2%E7%81%AB%E5%A2%99%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%90%AF%E5%8A%A8%E8%84%9A%E6%9C%AC)
科学上网直接用[ShellCrash](https://github.com/juewuy/ShellCrash)就好了

**Comment by luoyanghero** [comment]
给你推荐一个小爱音箱播放本地音乐脚本。
[https://github.com/zanjie1999/httpRandomMusic](https://github.com/zanjie1999/httpRandomMusic)
另外看到恩山论坛这个帖子[https://www.right.com.cn/forum/thread-8293693-1-1.html](https://www.right.com.cn/forum/thread-8293693-1-1.html)开启AX5400 ssh，需要openwrt虚拟机，开启移动热点...。你这几条命令就搞定了，666.

**Comment by mphin** [comment]
> 给你推荐一个小爱音箱播放本地音乐脚本。 https://github.com/zanjie1999/httpRandomMusic 另外看到恩山论坛这个帖子https://www.right.com.cn/forum/thread-8293693-1-1.html开启AX5400 ssh，需要openwrt虚拟机，开启移动热点...。你这几条命令就搞定了，666.

仓库里的所有步骤、文件以及相关信息均搜集自互联网，旨在提供学习和参考之用。感谢支持与关注！
