### ISSUE TITLE
sftp-server mount后仍然提示找不到

### ISSUE THREAD

**Issue by luoyanghero** [mphin/miwifi_tools#3]
系统信息：
miwifi_ra74_firmware_7937d_1.0.63.bin
```
root@XiaoQiang:~# cat /etc/os-release 
NAME="OpenWrt"
VERSION="18.06-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 18.06-SNAPSHOT"
VERSION_ID="18.06-snapshot"
HOME_URL="http://openwrt.org/"
BUG_URL="http://bugs.openwrt.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="unknown"
LEDE_BOARD="ipq/ipq50xx_64"
LEDE_ARCH="aarch64_cortex-a53"
LEDE_TAINTS="no-all busybox"
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt 18.06-SNAPSHOT unknown"
```
```
root@XiaoQiang:~# mount --bind /data/usr/libexec /usr/libexec
root@XiaoQiang:~# ls -la /usr/libexec/
drwxrwxr-x    2 root     root           304 Jul 14 23:02 .
drwxr-xr-x    8 root     root           127 Jan 30  2023 ..
-rwxrwxr-x    1 root     root           105 Jan 30  2023 login.sh
-rwxr-xr-x    1 root     root         74329 Jul 14 23:02 sftp-server
```
```
i 正在从状态 STATE_EXPECT_NEWKEYS 更改为 STATE_CONNECTION
i SEND: SERVICE_REQUEST[ssh-userauth]
i RECV: SERVICE_ACCEPT[ssh-userauth] -- OK
i SENT : USERAUTH_REQUEST [none]
i RECV : USERAUTH_FAILURE, continuations [publickey,password]
i SENT : USERAUTH_REQUEST [password]
i RECV : AUTH_SUCCESS
! ash: /usr/libexec/sftp-server: not found 
```

**Comment by mphin** [comment]
我错了我没有写清楚我这是ax5400电竞版，你是普通版的吧？a53架构用这个
https://fastly.jsdelivr.net/gh/mphin/miwifi_tools@main/ax5400/sftp-server

**Comment by luoyanghero** [comment]
> 我错了我没有写清楚我这是ax5400电竞版，你是普通版的吧？a53架构用这个 https://fastly.jsdelivr.net/gh/mphin/miwifi_tools@main/ax5400/sftp-server

感谢。我这是白色普通版，现在可以了。
之前不行，我是用scp上传。

**Comment by luoyanghero** [comment]
```
root@XiaoQiang:/data/auto_ssh# cat startup_script.sh 
#!/bin/sh
install() {
        # Add script to system autostart docker
        uci set firewall.startup_script=include
        uci set firewall.startup_script.type='script'
        uci set firewall.startup_script.path="/data/startup_script.sh"
        uci set firewall.startup_script.enabled='1'
        uci commit firewall
        echo -e "\033[32m  startup_script complete. \033[0m"
}
uninstall() {
    # Remove scripts from system autostart
    uci delete firewall.startup_script
    uci commit firewall
    echo -e "\033[33m startup_script  has been removed. \033[0m"
}

startup_script() {
        # Put your custom script here.
        echo "Starting custom scripts..."
#        mount --bind /data/usr/libexec /usr/libexec
}

main() {
    [ -z "$1" ] && startup_script && return
    case "$1" in
    install)
        install
        ;;
    uninstall)
        uninstall
        ;;
    *)
        echo -e "\033[31m Unknown parameter: $1 \033[0m"
        return 1
        ;;
    esac
}


main "$@"
```
发现开机脚本`mount --bind /data/usr/libexec /usr/libexec`是注释掉的。
为啥执行了`mount --bind /data/usr/libexec /usr/libexec`，重启了还在。
没有搞明白官方固件里面的文件挂载关系。
```
root@XiaoQiang:/data/auto_ssh# df
Filesystem           1K-blocks      Used Available Use% Mounted on
mtd:ubi_rootfs           20480     20480         0 100% /
tmpfs                   197572      4508    193064   2% /tmp
ubi1_0                   23852       436     22164   2% /data
ubi1_0                   23852       436     22164   2% /userdisk
mtd:ubi_rootfs           20480     20480         0 100% /userdisk/data
ubi1_0                   23852       436     22164   2% /etc/config
ubi1_0                   23852       436     22164   2% /etc/datacenterconfig
ubi1_0                   23852       436     22164   2% /etc/smartcontroller
ubi1_0                   23852       436     22164   2% /etc/parentalctl
ubi1_0                   23852       436     22164   2% /etc/smartvpn
ubi1_0                   23852       436     22164   2% /etc/ppp
ubi1_0                   23852       436     22164   2% /etc/crontabs
ubi1_0                   23852       436     22164   2% /ini
tmpfs                      512        24       488   5% /dev
ubi1_0                   23852       436     22164   2% /usr/libexec
root@XiaoQiang:/data/auto_ssh# ls -la /usr/libexec/
drwxrwxr-x    2 root     root           304 Jul 17 07:52 .
drwxr-xr-x    8 root     root           127 Jan 30  2023 ..
-rwxrwxr-x    1 root     root           105 Jan 30  2023 login.sh
-rwxr-xr-x    1 root     root         91297 Jul 17 07:52 sftp-server
root@XiaoQiang:/data/auto_ssh# ls -la /data/usr/libexec/
drwxrwxr-x    2 root     root           304 Jul 17 07:52 .
drwxr-xr-x    4 root     root           288 Jul 14 23:02 ..
-rwxrwxr-x    1 root     root           105 Jan 30  2023 login.sh
-rwxr-xr-x    1 root     root         91297 Jul 17 07:52 sftp-server
```

**Comment by mphin** [comment]
> ```
> root@XiaoQiang:/data/auto_ssh# cat startup_script.sh 
> #!/bin/sh
> install() {
>         # Add script to system autostart docker
>         uci set firewall.startup_script=include
>         uci set firewall.startup_script.type='script'
>         uci set firewall.startup_script.path="/data/startup_script.sh"
>         uci set firewall.startup_script.enabled='1'
>         uci commit firewall
>         echo -e "\033[32m  startup_script complete. \033[0m"
> }
> uninstall() {
>     # Remove scripts from system autostart
>     uci delete firewall.startup_script
>     uci commit firewall
>     echo -e "\033[33m startup_script  has been removed. \033[0m"
> }
> 
> startup_script() {
>         # Put your custom script here.
>         echo "Starting custom scripts..."
> #        mount --bind /data/usr/libexec /usr/libexec
> }
> 
> main() {
>     [ -z "$1" ] && startup_script && return
>     case "$1" in
>     install)
>         install
>         ;;
>     uninstall)
>         uninstall
>         ;;
>     *)
>         echo -e "\033[31m Unknown parameter: $1 \033[0m"
>         return 1
>         ;;
>     esac
> }
> 
> 
> main "$@"
> ```
> 
> 发现开机脚本`mount --bind /data/usr/libexec /usr/libexec`是注释掉的。 为啥执行了`mount --bind /data/usr/libexec /usr/libexec`，重启了还在。 没有搞明白官方固件里面的文件挂载关系。
> 
> ```
> root@XiaoQiang:/data/auto_ssh# df
> Filesystem           1K-blocks      Used Available Use% Mounted on
> mtd:ubi_rootfs           20480     20480         0 100% /
> tmpfs                   197572      4508    193064   2% /tmp
> ubi1_0                   23852       436     22164   2% /data
> ubi1_0                   23852       436     22164   2% /userdisk
> mtd:ubi_rootfs           20480     20480         0 100% /userdisk/data
> ubi1_0                   23852       436     22164   2% /etc/config
> ubi1_0                   23852       436     22164   2% /etc/datacenterconfig
> ubi1_0                   23852       436     22164   2% /etc/smartcontroller
> ubi1_0                   23852       436     22164   2% /etc/parentalctl
> ubi1_0                   23852       436     22164   2% /etc/smartvpn
> ubi1_0                   23852       436     22164   2% /etc/ppp
> ubi1_0                   23852       436     22164   2% /etc/crontabs
> ubi1_0                   23852       436     22164   2% /ini
> tmpfs                      512        24       488   5% /dev
> ubi1_0                   23852       436     22164   2% /usr/libexec
> root@XiaoQiang:/data/auto_ssh# ls -la /usr/libexec/
> drwxrwxr-x    2 root     root           304 Jul 17 07:52 .
> drwxr-xr-x    8 root     root           127 Jan 30  2023 ..
> -rwxrwxr-x    1 root     root           105 Jan 30  2023 login.sh
> -rwxr-xr-x    1 root     root         91297 Jul 17 07:52 sftp-server
> root@XiaoQiang:/data/auto_ssh# ls -la /data/usr/libexec/
> drwxrwxr-x    2 root     root           304 Jul 17 07:52 .
> drwxr-xr-x    4 root     root           288 Jul 14 23:02 ..
> -rwxrwxr-x    1 root     root           105 Jan 30  2023 login.sh
> -rwxr-xr-x    1 root     root         91297 Jul 17 07:52 sftp-server
> ```
> 
> 另外AX5400白色普通版，默认 终端上下键有历史记录功能。不需要`mount --bind /data/root /root`

我没用过普通版。。。太奇怪了不管他拉，我这电竞版主目录都是只读不可写/etc目录都是重启会恢复。可玩性太低了还要挂载上去，装个SFTP装个ShellCrash科学上网就不管他了。话说你那普通版分区都是可写得吧？要不然默认/root竟然可写。内存好像是512？科学够吗？

**Comment by luoyanghero** [comment]
> 我没用过普通版。。。太奇怪了不管他拉，我这电竞版主目录都是只读不可写/etc目录都是重启会恢复。可玩性太低了还要挂载上去，装个SFTP装个ShellCrash科学上网就不管他了。话说你那普通版分区都是可写得吧？要不然默认/root竟然可写。内存好像是512？科学够吗？

刚才流程有错。现在是这样的流程：
```
root@XiaoQiang:/data/auto_ssh# cat startup_script.sh 
#!/bin/sh
install() {
        # Add script to system autostart docker
        uci set firewall.startup_script=include
        uci set firewall.startup_script.type='script'
        uci set firewall.startup_script.path="/data/startup_script.sh"
        uci set firewall.startup_script.enabled='1'
        uci commit firewall
        echo -e "\033[32m  startup_script complete. \033[0m"
}
uninstall() {
    # Remove scripts from system autostart
    uci delete firewall.startup_script
    uci commit firewall
    echo -e "\033[33m startup_script  has been removed. \033[0m"
}

startup_script() {
        # Put your custom script here.
        echo "Starting custom scripts..."
#        mount --bind /data/usr/libexec /usr/libexec
        (sleep 20; mount --bind /data/usr/libexec /usr/libexec) &
        
        sleep 20;
        ln -sf /data/etc/custom_hosts /etc/custom_hosts
}

main() {
    [ -z "$1" ] && startup_script && return
    case "$1" in
    install)
        install
        ;;
    uninstall)
        uninstall
        ;;
    *)
        echo -e "\033[31m Unknown parameter: $1 \033[0m"
        return 1
        ;;
    esac
}


main "$@"
root@XiaoQiang:/data/auto_ssh# ./startup_script.sh install
  startup_script complete. 
root@XiaoQiang:/data/auto_ssh# reboot
```
但是重启还是没有生效。上面操作哪里有问题吗？
```
root@XiaoQiang:/data/auto_ssh# ls /usr/libexec/
login.sh
root@XiaoQiang:/data/auto_ssh# ls /data/usr/libexec/
login.sh     sftp-server
root@XiaoQiang:/data/auto_ssh# ls -la /etc/custom_hosts 
-rw-rw-r--    1 root     root            36 Jan 30  2023 /etc/custom_hosts
```
/root可以写。分区可写咋个看？
```
root@XiaoQiang:~# pwd
/root
root@XiaoQiang:~# ls -la
drwxr-xr-x    2 root     root             3 Jan 30  2023 .
drwxr-xr-x   22 root     root           349 Jan 30  2023 ..
```
普通版内存是512MB，配置跟电竞版一样的。科学应该够吧？

**Comment by mphin** [comment]
> 436     22164   2% /etc/conf

startup_script.sh应该在/data目录下，不应该是/data/auto_ssh目录。
`uci set firewall.startup_script.path="/data/startup_script.sh"`

**Comment by luoyanghero** [comment]
搞定了，666
